modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/Terrails/stat-tinkerer"
license = "MIT"

[[mods]]
modId = "stattinkerer"
version = "${version}"

displayName = "Stat Tinkerer"
authors = "Terrails"
description = ''' Modify behaviour of various stat mechanics. '''

logoFile = "stattinkerer.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since its a client only mod

[[dependencies.stattinkerer]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.stattinkerer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "CLIENT"
