org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

## Project
minecraft_version=26.2
min_minecraft_version=26.1.2
supported_minecraft_versions=26.1.2,26.2
mod_version=26.2.0

curseforge_id=258168
modrinth_id=UAfajCcY

## Fabric
#https://fabricmc.net/develop/
fabric_loader_version=0.19.3
min_fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2
min_fabric_api_version=0.155.2+26.1.2
#https://github.com/TheElectronWill/night-config
nightconfig_version=3.9.0

## NeoForge
#https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.40-beta
min_neoforge_version=26.1.2.93