modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Terrails/stat-tinkerer"
license = "MIT"

[[mods]]
modId = "stattinkerer"
version = "${version}"

displayName = "Stat Tinkerer"
authors = "Terrails"
description = ''' Modify behaviour of various stat mechanics. '''

logoFile = "stattinkerer.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since its a client only mod

[[dependencies.stattinkerer]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.stattinkerer]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"
