modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Terrails/stat-tinkerer"
license = "MIT"

[[mods]]
modId = "stattinkerer"
version = "${version}"

displayName = "Stat Tinkerer"
authors = "Terrails"
description = ''' Modify behaviour of various stat mechanics. '''

logoFile = "stattinkerer.png"
displayTest = "MATCH_VERSION"

[[dependencies.stattinkerer]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stattinkerer]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"
